### ISSUE TITLE
Remote video is not appearing

### ISSUE THREAD

**Issue by gkunwar** [mojolingo/talking_stick#33]
Hi All,

I am trying to integrate talking_stick to my rails application. I followed all the steps from the readme. But I have a problem. My partner video is not appearing.

Is there anything that I messed?
Thanks in advance.

**Comment by bklang** [comment]
This is almost always an issue with networking, and not with Talking Stick or WebRTC directly.  A few things you can try:

* The simplest test is to set up two windows/browser tabs on the same computer, and make sure they can see/hear each other
* To test with two computers, try two computers on the same local network. Also ensure that their firewalls are off (at least for testing)
* If you want to work with two computers on different networks, you'll almost certainly need STUN and TURN servers. [This link](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/) may help explain it better

**Comment by gkunwar** [comment]
Thank you @bklang for the quick response. Today I tested again and found it was different reason. It works fine now.
Thank you again.

**Comment by bklang** [comment]
Would you let us know what you found and how you fixed it? Someone may come across this issue in the future.

**Comment by gkunwar** [comment]
@bklang This was because of Bullet gem. It was fixed when I remove bullet gem from my application. Need to fix this issue.

**Comment by erhimanshusaxena** [comment]
@gkunwar I am trying to open in same browser with different tab, still not working, any ideas ? Only spinner is visible.

Thanks

**Comment by gkunwar** [comment]
@erhimanshusaxena Does it works with two different browser?
